# Generated by Django 4.1 on 2022-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rank',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Basliq'),
        ),
    ]
