# Generated by Django 4.1 on 2022-08-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0002_rename_rank_course_rate_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(max_length=300),
        ),
    ]
